apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank-api
  template:
    metadata:
      labels:
        app: bank-api
    spec:
      containers:
      - name: bank-api
        image: YOUR_REPO_URL/indira-bank-api
        ports:
        - containerPort: 5000
#kubectl apply -f deployment.yaml